### ISSUE TITLE
Disappearing food

### ISSUE THREAD

**Issue by thunderkai** [TeamIf/FireEmblemIf-FanTranslation#14]
Food does not appear when you feed Lilith

**Comment by ShadySheikah** [comment]
This is a problem the original group noticed, as well. Unfortunately, we don't know how to fix it.

The issue stems from the translation itself. The game seems to look up the food models based on the literal name of the food, so since the food names have been translated into English, the game can't find the correct object to load.

We're still looking for a possible workaround to this, but it's likely we won't find one. Sorry!
