### ISSUE TITLE
Hoshido path selection and yes/no buttons

### ISSUE THREAD

**Issue by laicar** [TeamIf/FireEmblemIf-FanTranslation#3]
I "updated" the 4.0 patch with one file for My Castle menu but the yes/no buttons are still in Japanese.

When choosing the Hoshido path, the text window goes beyond the screen, and there is a missing space in the text (maybe the boxing happens automatically and the missing space was a new line?). The Nohr path windows works fine.

Moreover, the Hoshidan Woman (female villager) in the castle doesn't have anything as staff store welcome line.

**Comment by jftm999** [comment]
adding to the post, in Nohr path, the Nohrian woman in my castle (nohrian shop) also doesn't has a welcome line

**Comment by laicar** [comment]
I haven't played further so I couldn't say but maybe I didn't replace the files correctly before patching. I have the 4.0 patch zip with the MyCastle.bin.lz from a following commit.

**Comment by jftm999** [comment]
this is a quote from member (Team if) replying to someone who had similar issue in the first page of the thread: "We only included in the patch files that were completely translated. There were a few files that were partially translated, such as the Forge and some of the Armory and Hot Spring lines. We're working on finishing those soon, but if you want the previous lines back, you can use the files from the last patch and copy them over into this patch's m folder. Their filenames are 下画面セリフ_武器屋道具屋.bin.lz, 死亡.bin.lz, and 店番_牢屋.bin.lz. Sorry about that"

See if that's helps

**Comment by ShadySheikah** [comment]
Both the path selection descriptions and the yes/no options have been fixed, and the updated files have been committed.

Regarding the descriptions, our editor assigned to revising the story chapters mistook them for another conversation and edited them as such, resulting in missing spaces once processed by the game. The file has been reverted to its 3.0 version.

The yes/no buttons not being translated turned out to be the result of a naming issue. Almost every interface-related file has an English title, with the exception of the file in question. At some point, the title was translated and renamed to match the others, and when 4.0 was assembled, we missed the inconsistency.
