### ISSUE TITLE
Can't view the wike page for patching the game

### ISSUE THREAD

**Issue by firelad97** [TeamIf/FireEmblemIf-FanTranslation#32]
https://github.com/TeamIf/FireEmblemIf-FanTranslation/wiki/Using-the-Provided-Patcher

I can't view this page at all. Kept telling me I do not have the permission to edit - I'm not trying to edit. I'm trying to view the page so I can patch my game.

**Comment by purposelycryptic** [comment]
IIRC, the Patcher is outdated and should not be used - they likely removed that page from the wiki because of that, but accidentally left links to it, which is why you are getting the 'do not have the permission to edit' message; the page doesn't exist, so GitHub thinks you are trying to create it, which you do not have the access rights to do.

You might be able to use [this](https://github.com/ShadySheikah/IfPatcher/releases), assuming your copy is already decrypted, but I never tried, as I went the "traditional" route of taking the game apart, replacing the necessary parts, and putting it back together. I'm also not sure if that patcher has the patch built-in, or if it will take the translation files you give it as well (It isn't up to the latest version).

On that note, you should also be aware that this Fan Translation was never completed, and **a lot** is still untranslated - many support conversations are missing (pretty much the whole second generation, I believe), as is, seemingly, much of the _'Revelations/Hidden Kingdom'_ Arc, and various DLCs. See [here](https://serenesforest.net/forums/index.php?/topic/67613-fire-emblem-if-fan-translation-under-new-management/) for more details on the patch itself. 

An awesome individual going by **Harwy** translated the rest of _'Revelations/Hidden Kingdom'_, but that was done separately from this, and finding the patch files for that was near impossible through legitimate channels (and most less legitimate ones), back when I was trying to piece together everything already completed. I had started on translating the remaining untranslated parts back in March, but I am seriously ill, and only shortly after starting, my health deteriorated beyond the point of being able to work on it. Anyway...

Assuming you have both **If** and **Fates**, you may be able to create a "Frankenstein" version, using the Nintendo-localized parts from **Fates** to fill in the missing pieces of the translation. I know somebody on the forums did so, and I was considering doing so myself before I ended up too sick to even play games anymore.

So...

## To manually patch your game (going by 5 month old memory), you'll need:

- [ihaveamac/3DS-rom-tools](https://github.com/ihaveamac/3DS-rom-tools)
   - which also has a lot of useful information - you'll likely be relying on [this wiki](https://github.com/ihaveamac/3DS-rom-tools/wiki) A LOT
- [SciresM/3DS-Builder](https://github.com/SciresM/3DS-Builder)
   - something about the other versions not handling Japanese filenames correctly? Pretty sure the **SciresM** version was needed for FE.
- [profi200/Project_CTR](https://github.com/profi200/Project_CTR)
   - Pretty sure I needed to use this...
- A decent frustration threshold

It may sound like a lot, but I managed to do it, and I had a high fever, was periodically coughing up blood, and barely able to walk at the time, so it can't be _that_ hard :-)

Oh, and while I don't think you'll need [SciresM/FEAT](https://github.com/SciresM/FEAT), since you won't personally be editing/translating any files, I'll leave the link there, just in case
