### ISSUE TITLE
Chapter 5 - 7, Minor Errors and Oddities

### ISSUE THREAD

**Issue by SoftwareGuy** [TeamIf/FireEmblemIf-FanTranslation#9]
**Chapter 5**
During the fight where Kamui's dragon powers activate, Ryouma says:
> If we want to win this battle, we'll need Kamui' s Dragon powers..

There is excess white space between the ' and the 's'.

**Chapter 6**
Marx's line...
> ...You reckless fool. All who resist will meet their end here.

Repeats twice, then the battle continues.

**Chapter 7**
The description on the bottom screen for the "A Gathering of Spirits" chapter is untranslated.

_Please leave this open that way I can keep noting down any oddities. Thanks!_

**Comment by Joshkinz** [comment]
Issue in chapter 5 fixed, tomorrow I will fix chapters 6 and 7 and push an update. Thanks.

**Comment by ShadySheikah** [comment]
Chapter 6 fixed.

The description is actually part of the single system file we've yet to complete. It won't be completed by the next commit, but it should be ready by the next release.

It's been a couple months since this was opened, and all noted issues have been resolved. If you find any more issues, please feel free to open another one 👍
